on: [ push, pull_request ]
name: Continuous Integration
jobs:
  lint:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install golangci-lint
        run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.31.0
          golangci-lint --version

      - name: Lint
        run: |
          golangci-lint run --color=always -c .golangci.yml ./...

          cd native
          golangci-lint run --color=always -c ../.golangci.yml ./...

  test:
    strategy:
      matrix:
        go-version: [ 1.13.x, 1.14.x, 1.15.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls

      - name: Test
        run: |
          go test --tags=mock -v -race -covermode atomic "-coverprofile=profile.cov.tmp1" ./...

          # Remove some stuff from the profile...
          cat profile.cov.tmp1 | grep -v "echocat/slf4g/internal/test/" > profile.cov.tmp2
          cat profile.cov.tmp2 | grep -v "echocat/slf4g/internal/demo/" > profile.cov.tmp3
          cp profile.cov.tmp3 profile.cov

      - name: Test slf4g/native
        run: |
          cd native

          go test --tags=mock -v -race -covermode atomic "-coverprofile=profile.cov.tmp1" ./...

          cat profile.cov.tmp1 | grep -v "echocat/slf4g/native/internal/demo_" > profile.cov.tmp2
          cat profile.cov.tmp2 | grep -v "echocat/slf4g/native/color/prepare_" > profile.cov.tmp3
          cp profile.cov.tmp3 profile.cov

      - name: Send coverage slf4g
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          goveralls "-coverprofile=profile.cov" "-service=github" "-parallel" "-flagname=go-${{ matrix.go-version }}-${{ matrix.os }}-slf4g"

      - name: Send coverage slf4g/native
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd native
          goveralls "-coverprofile=profile.cov" "-service=github" "-parallel" "-flagname=go-${{ matrix.go-version }}-${{ matrix.os }}-slf4g-native"

  # notifies that all test jobs are finished.
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls

      - name: Send coverage finish
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          goveralls "-parallel-finish" "-service=github"
