on: [ push, pull_request ]
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint slf4g
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Lint slf4g/native
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: native
