on: [ push, pull_request ]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.13.x, 1.14.x, 1.15.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls

      - name: Test slf4g
        run: |
          go test -v -covermode atomic "-coverprofile=profile.cov.tmp1" ./...

          cat profile.cov.tmp1 | grep -v "echocat/slf4g/internal/test/" > profile.cov.tmp2
          cat profile.cov.tmp2 | grep -v "echocat/slf4g/internal/demo/" > profile.cov.tmp3
          cp profile.cov.tmp3 profile.cov

      - name: Send coverage slf4g
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          flag-name: go-${{ matrix.go-version }}-${{ matrix.os }}-slf4g
          parallel: true

      - name: Test slf4g/native
        run: |
          cd native
          go test --tags=mock -v -covermode atomic "-coverprofile=profile.cov.tmp1" ./...

          cat profile.cov.tmp1 | grep -v "echocat/slf4g/native/internal/demo_" > profile.cov.tmp2
          cat profile.cov.tmp2 | grep -v "echocat/slf4g/native/color/prepare_" > profile.cov.tmp3
          cp profile.cov.tmp3 profile.cov

      - name: Send coverage slf4g/native
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: native/profile.cov
          flag-name: go-${{ matrix.go-version }}-${{ matrix.os }}-slf4g-native
          parallel: true

  # notifies that all test jobs are finished.
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
